name: event_reminder_app
description: A new Flutter project for remembering important dates.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  
  
  
  # For Supabase integration
  supabase_flutter: ^2.5.0
  
  # For Arabic language support in the app
  flutter_localizations:
    sdk: flutter

  # For state management (Theme, Date format)
  provider: ^6.1.2

  # For profile picture selection
  image_picker: ^1.1.2

  
  # For the share functionality
  share_plus: ^9.0.0


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4
    
flutter_icons:
  android: true
  image_path: "تصميم بدون عنوان (1).jpg"
  
flutter:
  uses-material-design: true

